variables:
  DOCKER_DRIVER: overlay
  BOOTSTRAP_JS: "plugin/resources/assets/js/bootstrap.js"


stages:
  - test
  - staging
#  - deploy

test:
  tags:
    - docker
  image: misterio92/ci-php-node:3.0
  stage: test
  services:
    - name: docker:dind
  script:
    - touch .env
    - php composer.phar install --dev
    - cp -p .env.develop .env
    - php artisan key:generate
    - php vendor/phpunit/phpunit/phpunit --configuration phpunit.xml plugin/tests/Unit

# deploy:
#   tags:
#     - ained
#   stage: deploy
#   script:
#     -  pwd
#   #    git clone https://charon:1sg6MQyfXDEyKckZKphs@gitlab.cs.ttu.ee/ained/charon.git
#   only:
#     - dev
#     - master

try_create_production_artifacts:
  tags:
    - docker
  stage: staging
  image: misterio92/ci-php-node:4.0
  services:
    - name: docker:dind
  script:
    - ./create_prod_artifact.sh

create_production_artifacts:
  tags:
    - docker
  stage: staging
  image: misterio92/ci-php-node:4.0
  services:
    - name: docker:dind
  script:
    - ./create_prod_artifact.sh
  artifacts:
    paths:
      - $CI_PROJECT_DIR/charon
  only:
  - master
