variables:
  DOCKER_DRIVER: overlay


stages:
  - test
  - build
  - deploy
  - create_artifacts


test:
  tags:
    - develop
    - master
  image: docker:latest
  stage: test
  services:
    - name: docker:dind
  before_script:
    - docker container ls
    - docker images
  script:
    - whoami  # run tests somehow
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master


build:
  tags:
    - develop
    - master
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  before_script:
    - docker container ls
    - docker images
  script:
    - whoami  # build the js thingy
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master


deploy:
  tags:
    - develop
    - master
  image: $DOCKER_USER/arete:latest
  stage: deploy
  services:
    - name: docker:dind
  before_script:
    - docker container ls
    - docker images
  script:
    - cd ~/moodle/moodle_data/moodle/mod/charon
    - git pull
  #    git clone https://charon:1sg6MQyfXDEyKckZKphs@gitlab.cs.ttu.ee/ained/charon.git
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master


create_artifacts:
  tags:
    - develop
    - master
    - 101-ci-cd-create-zip-that-is-ready-to-be-installed-without-hacks
  script:
    - php -v
    #    - cp -a ./. $CI_PROJECT_DIR/artifacts/
  artifacts:
    paths:
      - $CI_PROJECT_DIR
