variables:
  DOCKER_DRIVER: overlay
  BOOTSTRAP_JS: "plugin/resources/assets/js/bootstrap.js"

stages:
  - test
  - build
  - deploy
  - integration test

unit_test:
  tags:
    - docker
  image: jaakkytt/ci-php-node:3.0
  stage: test
  services:
    - name: docker:dind
  script:
    - touch .env
    - php composer.phar install --dev
    - cp -p .env.dev .env
    - php artisan key:generate
    - php vendor/phpunit/phpunit/phpunit --coverage-text --colors=never --configuration phpunit.xml plugin/tests/Unit
  artifacts:
    paths:
      - $CI_PROJECT_DIR/coverage
    expire_in: 1 week

security-advisories-vulnerabilities:
  stage: test
  image: umutphp/php-docker-images-for-ci:7.4
  script:
    - local-php-security-checker

.builds:
  tags:
    - docker
  stage: build
  image: misterio92/ci-php-node:4.0
  services:
    - name: docker:dind
  script:
    - chmod +x create_prod_artifact.sh && ./create_prod_artifact.sh
  artifacts:
    paths:
      - $CI_PROJECT_DIR/charon

build_dev:
  extends: .builds
  artifacts:
    expire_in: 1 week
  only:
    - develop
    - /^release.*/

build_any:
  extends: .builds
  artifacts:
    expire_in: 1 day
  when: manual
  only:
    - /^bugfix*/
    - /^feature.*/

build:
  extends: .builds
  only:
  - master

.deploys:
  tags:
    - docker
  stage: deploy
  image: misterio92/ci-php-node:4.0
  environment:
    name: development
    url: http://$ENV_IP/moodle
  before_script:
    - eval $(ssh-agent -s)
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $ENV_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -r ./charon $SSH_USER@$ENV_IP:$MOD_PATH
    - ssh $SSH_USER@$ENV_IP "find \"$MOD_PATH/charon\" -type f -exec chmod 0644 {} \;"
    - ssh $SSH_USER@$ENV_IP "chown -R $MOODLE_USER_GROUP $MOD_PATH/charon"
    - ssh $SSH_USER@$ENV_IP "chmod -R 775 $MOD_PATH/charon/plugin/storage"
    - ssh $SSH_USER@$ENV_IP "find $MOD_PATH/charon/plugin/storage -type f -exec chmod 0664 {} \;"
    - ssh $SSH_USER@$ENV_IP "echo \"y\" | php $MOODLE_PATH/admin/cli/upgrade.php"
    - ssh $SSH_USER@$ENV_IP "php $MOODLE_PATH/admin/cli/purge_caches.php"

deploy_dev:
  extends: .deploys
  only:
    - develop

deploy_any:
  extends: .deploys
  when: manual
  only:
    - /^bugfix*/
    - /^feature.*/
    - /^release.*/

# Currently not in use
integration_test_dev:
  tags:
    - docker
  image: jaakkytt/ci-php-node:3.0
  stage: integration test
  services:
    - name: docker:dind
  before_script:
    - service mysql start
  script:
    - touch .env
    - php composer.phar install --dev
    - cp -p .env.dev .env
    - cat $INTEGRATION_DB_VARIABLES >> .env
    - php artisan key:generate
    - php vendor/phpunit/phpunit/phpunit --coverage-text --colors=never --configuration phpunit.xml
  only:
    - disabled
  artifacts:
    paths:
      - $CI_PROJECT_DIR/coverage
    expire_in: 1 week
