variables:
  DOCKER_DRIVER: overlay


stages:
  - test
  - build
  - deploy


test:
  tags:
    - dev
    - master
  image: docker:latest
  stage: test
  services:
    - name: docker:dind
  before_script:
    - docker container ls
    - docker images
  script:
    - whoami  # run tests somehow
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master


build:
  tags:
    - dev
    - master
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  before_script:
    - docker container ls
    - docker images
  script:
    - whoami  # build the js thingy
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master


deploy:
  tags:
    - dev
    - master
  image: $DOCKER_USER/arete:latest
  stage: deploy
  services:
    - name: docker:dind
  before_script:
    - docker container ls
    - docker images
  script:
    - cd ~/moodle/moodle_data/moodle/mod/
    - rm -rf charon/
    - git clone https://charon:1sg6MQyfXDEyKckZKphs@gitlab.cs.ttu.ee/ained/charon.git
    - cd charon
    - sudo php composer.phar install
    - sudo cp -p .env.example .env
    - sudo php artisan key:generate
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master
