version: '2'
services:

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8190:8080"

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './mariadb_data:/bitnami'
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
    driver: local
