version: '2'
services:

  moodle:
    image: 'bitnami/moodle:3.8.3'
    environment:
      - MARIADB_HOST=35.217.3.154
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=dev
      - MOODLE_PASSWORD=dev
    ports:
      - '81:80'
      - '444:443'
    volumes:
      - './moodle_data:/bitnami'

volumes:
  moodle_data:
    driver: local