version: '2'
services:

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8190:8080"

  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes

  moodle:
    image: 'bitnami/moodle:3.9.0'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=dev
      - MOODLE_PASSWORD=dev
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './moodle_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  moodle_data:
    driver: local
