version: '2'
services:

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8190:8080"

  mariadb:
    image: 'bitnami/mariadb:10.3'
    container_name: charon-db
    environment:
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=dev
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - "3306:3306"

  moodle:
    build:
      context: .
    container_name: charon-moodle
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=dev
      - MOODLE_USERNAME=dev
      - MOODLE_PASSWORD=dev
      - DEBUGGING=DEVELOPER
    ports:
      - '80:80'
      - '9717:443'
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - './..:/bitnami/moodle/mod/charon'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
